/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Highlighter;
import javax.swing.text.JTextComponent;

/**
 *
 * @author OLIVER
 */

public class frm_cadenas extends javax.swing.JFrame {

    /**
     * Creates new form frm_cadenas
     */
    private File ficheroa;
    public frm_cadenas() {
        initComponents();
        this.setTitle("Manejo de Cadenas");
        this.setLocationRelativeTo(null);
    }

    class resaltador extends DefaultHighlighter.DefaultHighlightPainter{
        public resaltador(Color  color){
            super(color);
        }
           
    }
    
    Highlighter.HighlightPainter resaltador = new resaltador(Color.orange);
    
    public void quitarResaltado(JTextComponent txt){
        Highlighter res = txt.getHighlighter();
        Highlighter.Highlight[] resa = res.getHighlights();
        for(int i=0;i<resa.length;i++){
                res.removeHighlight(resa[i]);
        }
         
    }
    
    public void resaltar(JTextComponent txt,String palabra){
            quitarResaltado(txt_entrada);
            try{
                Highlighter res = txt.getHighlighter();
                Document doc = txt.getDocument();
                String text = doc.getText(0,doc.getLength());
                int pos = 0;
                while((pos=text.toUpperCase().indexOf(palabra.toUpperCase(),pos))>=0){
                    res.addHighlight(pos, pos+palabra.length(), resaltador);
                    pos += palabra.length();
                }
            }catch(Exception ex){}
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_entrada = new javax.swing.JTextArea();
        btn_procesar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_murcielago = new javax.swing.JTextArea();
        lbl_longitud = new javax.swing.JLabel();
        lbl_primer = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_ultima = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        lbl_e = new javax.swing.JLabel();
        lbl_i = new javax.swing.JLabel();
        lbl_o = new javax.swing.JLabel();
        lbl_u = new javax.swing.JLabel();
        lbl_central = new javax.swing.JLabel();
        lbl_primerap = new javax.swing.JLabel();
        lbl_ultimap = new javax.swing.JLabel();
        lbl_centrop = new javax.swing.JLabel();
        lbl_par = new javax.swing.JLabel();
        lbl_impar = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_longitudletras = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        menu_barra = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        menu_nuevo = new javax.swing.JMenuItem();
        menu_abrir = new javax.swing.JMenuItem();
        menu_guardar = new javax.swing.JMenuItem();
        menu_guardarCo = new javax.swing.JMenuItem();
        menu_editar = new javax.swing.JMenu();
        menu_copiar = new javax.swing.JMenuItem();
        menu_cortar = new javax.swing.JMenuItem();
        menu_pegar = new javax.swing.JMenuItem();
        menu_buscar = new javax.swing.JMenuItem();
        menu_reemplazar = new javax.swing.JMenuItem();

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Repeticiones de \"O\" \"o\" ó \"ó\"");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));
        jPanel1.setToolTipText("");

        lbl_titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("Manejo de Cadenas");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese un texto o abra un archivo:");

        txt_entrada.setColumns(20);
        txt_entrada.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_entrada.setRows(5);
        jScrollPane1.setViewportView(txt_entrada);

        btn_procesar.setBackground(new java.awt.Color(255, 102, 0));
        btn_procesar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_procesar.setForeground(new java.awt.Color(0, 0, 102));
        btn_procesar.setText("click para continual");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Longitud del texto............");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total de palabras............");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Primera letra del texto.....");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ultima letra del texto.......");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Letra central del texto......");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Primera palabra...............");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Palabra central.................");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ultima palabra.................");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Repeticiones de \"A\" \"a\" ó \"á\"");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Repeticiones de \"E\" \"e\" ó \"é\"");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Repeticiones de \"I\" \"i\" ó \"í\"");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Repeticiones de \"O\" \"o\" ó \"ó\"");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Repeticiones de \"U\" \"u\" ó \"ú\"");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Palabras con cantidad de caracteres par");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Palabras con cantidad de caracteres impar");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Traducción a clave murcielago");

        txt_murcielago.setEditable(false);
        txt_murcielago.setColumns(20);
        txt_murcielago.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_murcielago.setRows(5);
        jScrollPane2.setViewportView(txt_murcielago);

        lbl_longitud.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_longitud.setForeground(new java.awt.Color(51, 255, 0));

        lbl_primer.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_primer.setForeground(new java.awt.Color(51, 255, 0));

        lbl_total.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(51, 255, 0));

        lbl_ultima.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_ultima.setForeground(new java.awt.Color(51, 255, 0));

        lbl_a.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_a.setForeground(new java.awt.Color(51, 255, 0));

        lbl_e.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_e.setForeground(new java.awt.Color(51, 255, 0));

        lbl_i.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_i.setForeground(new java.awt.Color(51, 255, 0));

        lbl_o.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_o.setForeground(new java.awt.Color(51, 255, 0));

        lbl_u.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_u.setForeground(new java.awt.Color(51, 255, 0));

        lbl_central.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_central.setForeground(new java.awt.Color(51, 255, 0));

        lbl_primerap.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_primerap.setForeground(new java.awt.Color(51, 255, 0));

        lbl_ultimap.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_ultimap.setForeground(new java.awt.Color(51, 255, 0));

        lbl_centrop.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_centrop.setForeground(new java.awt.Color(51, 255, 0));

        lbl_par.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_par.setForeground(new java.awt.Color(51, 255, 0));

        lbl_impar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_impar.setForeground(new java.awt.Color(51, 255, 0));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Longitud de letras..........");

        lbl_longitudletras.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_longitudletras.setForeground(new java.awt.Color(51, 255, 0));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Longitud del texto............");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(201, 201, 201))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_longitudletras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                                .addComponent(lbl_central, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_ultima, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_primer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_primerap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_centrop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_ultimap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(113, 113, 113)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_a, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_e, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbl_i, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbl_o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_u, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_par, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_impar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(btn_procesar))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(217, 217, 217)
                        .addComponent(btn_procesar))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3)
                                                .addComponent(lbl_a, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel4)
                                                                .addComponent(jLabel12))
                                                            .addComponent(lbl_e, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel5)
                                                                .addComponent(jLabel13))
                                                            .addComponent(lbl_primer, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lbl_i, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel21)
                                                        .addComponent(lbl_o, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel11)))
                                            .addComponent(lbl_ultima, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel16))
                                            .addComponent(lbl_central, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lbl_u, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel17))
                                    .addComponent(lbl_par, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_primerap, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel18))
                            .addComponent(lbl_impar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_centrop, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_ultimap, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(lbl_longitudletras, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_barra.setBackground(new java.awt.Color(0, 0, 0));

        menu_archivo.setBackground(new java.awt.Color(0, 0, 0));
        menu_archivo.setForeground(new java.awt.Color(255, 255, 255));
        menu_archivo.setText("Archivo");
        menu_archivo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        menu_nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_nuevo.setBackground(new java.awt.Color(0, 0, 0));
        menu_nuevo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        menu_nuevo.setText("Nuevo");
        menu_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_nuevoActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_nuevo);

        menu_abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_abrir.setBackground(new java.awt.Color(0, 0, 0));
        menu_abrir.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_abrir.setForeground(new java.awt.Color(255, 255, 255));
        menu_abrir.setText("Abrir");
        menu_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_abrirActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_abrir);

        menu_guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_guardar.setBackground(new java.awt.Color(0, 0, 0));
        menu_guardar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_guardar.setForeground(new java.awt.Color(255, 255, 255));
        menu_guardar.setText("Guardar");
        menu_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guardarActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_guardar);

        menu_guardarCo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        menu_guardarCo.setBackground(new java.awt.Color(0, 0, 0));
        menu_guardarCo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_guardarCo.setForeground(new java.awt.Color(255, 255, 255));
        menu_guardarCo.setText("Guardar Como");
        menu_guardarCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guardarCoActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_guardarCo);

        menu_barra.add(menu_archivo);

        menu_editar.setBackground(new java.awt.Color(0, 0, 0));
        menu_editar.setForeground(new java.awt.Color(255, 255, 255));
        menu_editar.setText("Editar");
        menu_editar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        menu_copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_copiar.setBackground(new java.awt.Color(0, 0, 0));
        menu_copiar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_copiar.setForeground(new java.awt.Color(255, 255, 255));
        menu_copiar.setText("Copiar");
        menu_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_copiarActionPerformed(evt);
            }
        });
        menu_editar.add(menu_copiar);

        menu_cortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_cortar.setBackground(new java.awt.Color(0, 0, 0));
        menu_cortar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_cortar.setForeground(new java.awt.Color(255, 255, 255));
        menu_cortar.setText("Cortar");
        menu_cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cortarActionPerformed(evt);
            }
        });
        menu_editar.add(menu_cortar);

        menu_pegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_pegar.setBackground(new java.awt.Color(0, 0, 0));
        menu_pegar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_pegar.setForeground(new java.awt.Color(255, 255, 255));
        menu_pegar.setText("Pegar");
        menu_pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pegarActionPerformed(evt);
            }
        });
        menu_editar.add(menu_pegar);

        menu_buscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_buscar.setBackground(new java.awt.Color(0, 0, 0));
        menu_buscar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_buscar.setForeground(new java.awt.Color(255, 255, 255));
        menu_buscar.setText("Buscar");
        menu_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_buscarActionPerformed(evt);
            }
        });
        menu_editar.add(menu_buscar);

        menu_reemplazar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_reemplazar.setBackground(new java.awt.Color(0, 0, 0));
        menu_reemplazar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menu_reemplazar.setForeground(new java.awt.Color(255, 255, 255));
        menu_reemplazar.setText("Reemplazar");
        menu_reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_reemplazarActionPerformed(evt);
            }
        });
        menu_editar.add(menu_reemplazar);

        menu_barra.add(menu_editar);

        setJMenuBar(menu_barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(269, 269, 269))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void longitud(){
        lbl_longitud.setText(Integer.toString(txt_entrada.getText().length()));
    }
    public void total(){
        double c=0, comparacion=0;
        StringTokenizer palabras = new StringTokenizer(txt_entrada.getText());
        lbl_total.setText(""+palabras.countTokens());
        String primero = palabras.nextToken();
        lbl_primerap.setText(primero);
        String ultimo = "", centro= "";
        comparacion = Double.parseDouble(lbl_total.getText())/2;
        while(palabras.hasMoreElements()){
            ultimo = palabras.nextToken();
            c++;
            if(c==comparacion || c+0.5==comparacion){
                centro = ultimo;
            }
        }
        if(ultimo==""){
            ultimo = primero;
            centro = ultimo;
        }
        lbl_centrop.setText(centro);
        lbl_ultimap.setText(ultimo); 
    }
    
    public void primera(){
        char primer = txt_entrada.getText().charAt(0);
        char b;
        if(primer == ' ' || primer == '.' || primer == '\n' || primer == ','){
         for(int i = 0; i<txt_entrada.getText().length();i++){
             b = txt_entrada.getText().charAt(i);
             if(b != ' ' && b != '.'&& b != '\n'&& b != ','){
                primer = b;
                break;
             }
         }
        }
        lbl_primer.setText(Character.toString(primer));
    }
    public void ultima(){
        int con =txt_entrada.getText().length()-1;
        char ultima = txt_entrada.getText().charAt(con);
        char b;
        if(ultima == ' ' || ultima == '.' || ultima == '\n' || ultima == ','|| ultima == '?'){
            
         for(int i = con; i>=0;i--){
             b = txt_entrada.getText().charAt(i);
             if(b != ' ' && b != '.'&& b != '\n'&& b != ',' && b!='?'){
                ultima = b;
                break;
             }
         }
        }
        lbl_ultima.setText(Character.toString(ultima));
    }
    
    public void central(){
        char a = txt_entrada.getText().charAt(txt_entrada.getText().length()/2);
        lbl_central.setText(Character.toString(a));
    }
    
    public void encontrarA (){
        char a;
        int letras = 0;
        for(int i = 0; i<txt_entrada.getText().length(); i++){
            a = txt_entrada.getText().charAt(i);
            if(a == 'a'||a == 'A'||a == 'á'||a == 'Á'){
                letras++;
            }
        }
        lbl_a.setText(Integer.toString(letras));
    }
    
    public void encontrarE (){
        char a;
        int letras = 0;
        for(int i = 0; i<txt_entrada.getText().length(); i++){
            a = txt_entrada.getText().charAt(i);
            if(a == 'e'||a == 'E'||a == 'é'||a == 'É'){
                letras++;
            }
        }
        lbl_e.setText(Integer.toString(letras));
    }
    
    public void encontrarI (){
        char a;
        int letras = 0;
        for(int i = 0; i<txt_entrada.getText().length(); i++){
            a = txt_entrada.getText().charAt(i);
            if(a == 'i'||a == 'I'||a == 'í'||a == 'Í'){
                letras++;
            }
        }
        lbl_i.setText(Integer.toString(letras));
    }
    
    public void encontrarO (){
        char a;
        int letras = 0;
        for(int i = 0; i<txt_entrada.getText().length(); i++){
            a = txt_entrada.getText().charAt(i);
            if(a == 'o'||a == 'O'||a == 'ó'||a == 'Ó'){
                letras++;
            }
        }
        lbl_o.setText(Integer.toString(letras));
    }
    
    public void encontrarU (){
        char a;
        int letras = 0;
        for(int i = 0; i<txt_entrada.getText().length(); i++){
            a = txt_entrada.getText().charAt(i);
            if(a == 'u'||a == 'U'||a == 'ú'||a == 'Ú'){
                letras++;
            }
        }
        lbl_u.setText(Integer.toString(letras));
    }
    
    public void par(){
        StringTokenizer palabras = new StringTokenizer(txt_entrada.getText());
        String elemento = "", count="";
        double num=0,comparacion=0;
        int par=0 , impar=0;
        while(palabras.hasMoreElements()){
            elemento = palabras.nextToken();
            num = elemento.length();
            comparacion = Math.round(num/2);
            if(comparacion == num/2){
                par++;
            }
            else{
                impar++;
            }
        }
        lbl_par.setText(Integer.toString(par));
        lbl_impar.setText(Integer.toString(impar));
    }
    
    public void clave_murcielago(){
        char a;
        int letras = 0;
        txt_murcielago.setText("");
        for(int i = 0; i<txt_entrada.getText().length(); i++){
            a = txt_entrada.getText().charAt(i);
            if(a=='m'||a=='M'){
                txt_murcielago.append("0");
            }
            else if(a=='u'||a=='U'||a=='ú'||a=='Ú'){
                txt_murcielago.append("1");
            }
            else if(a=='r'||a=='R'){
                txt_murcielago.append("2");
            }
            else if(a=='c'||a=='C'){
                txt_murcielago.append("3");
            }
            else if(a=='i'||a=='I'||a=='í'||a=='Í'){
                txt_murcielago.append("4");
            }
            else if(a=='e'||a=='E'||a=='é'||a=='É'){
                txt_murcielago.append("5");
            }
            else if(a=='l'||a=='L'){
                txt_murcielago.append("6");
            }
            else if(a=='a'||a=='A'||a=='á'||a=='Á'){
                txt_murcielago.append("7");
            }
            else if(a=='g'||a=='G'){
                txt_murcielago.append("8");
            }
            else if(a=='o'||a=='O'||a=='ó'||a=='Ó'){
                txt_murcielago.append("9");
            }
            else{
                txt_murcielago.append(Character.toString(a));
            }
        }
    }
    
    void longitudLetras(){
        int letras = 0;
        char valido[]={'a','b','c','d','e','f','g','h','i','j','k','l','m','n','ñ','o'
        ,'p','q','r','s','t','u','v','w','x','y','z'};
        String texto = txt_entrada.getText().toLowerCase();
        for(int i=0;i<texto.length();i++){
            char validos = texto.charAt(i);
            for (int j=0;j<valido.length;j++){
                if(validos == valido[j]){
                    letras++;
                    break;
                }
            }
            /*if(validos!=' '){
                letras++;
            }*/
        }
        lbl_longitudletras.setText(Integer.toString(letras));
    }
    
    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
        // TODO add your handling code here:
        try{
        longitud();
        longitudLetras();
        total();
        primera();
        ultima();
        central();
        encontrarA();
        encontrarE();
        encontrarI();
        encontrarO();
        encontrarU();
        par();
        clave_murcielago();
        }catch(Exception ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, "No ha ingresado nada en el campo de entrada!!","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void menu_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_copiarActionPerformed
        txt_entrada.copy();
    }//GEN-LAST:event_menu_copiarActionPerformed

    private void menu_cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cortarActionPerformed
        txt_entrada.cut();
    }//GEN-LAST:event_menu_cortarActionPerformed

    private void menu_pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pegarActionPerformed
        txt_entrada.paste();
    }//GEN-LAST:event_menu_pegarActionPerformed

    private void menu_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_buscarActionPerformed
        int conta=0;
        String elemento;
        StringTokenizer palabras = new StringTokenizer(txt_entrada.getText());
        String buscar = JOptionPane.showInputDialog(rootPane,"Ingrese la palabra que desea buscar:","Buscar",JOptionPane.PLAIN_MESSAGE);
        
        while(palabras.hasMoreElements()){
            elemento = palabras.nextToken();
            if(elemento.equals(buscar)||elemento.equals(buscar+".")||elemento.equals(buscar+",")||elemento.equals(buscar+";")||elemento.equals(buscar+":")){
                conta++;
            }
        }
        JOptionPane.showMessageDialog(rootPane, Integer.toString(conta)+" coincidencias encontradas","Coincidencias",JOptionPane.INFORMATION_MESSAGE);
        resaltar(txt_entrada,buscar);
    }//GEN-LAST:event_menu_buscarActionPerformed

    private void menu_reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_reemplazarActionPerformed
        int conta=0;
        String buscar, elemento, reemplazar, resultado;
        StringTokenizer palabras = new StringTokenizer(txt_entrada.getText());
        buscar = JOptionPane.showInputDialog(rootPane,"Ingrese la palabra que desea buscar:","Buscar",JOptionPane.PLAIN_MESSAGE);
        while(palabras.hasMoreElements()){
            elemento = palabras.nextToken();
            if(elemento.equals(buscar)||elemento.equals(buscar+".")||elemento.equals(buscar+",")||elemento.equals(buscar+";")||elemento.equals(buscar+":")){
                conta++;
            }
        }
        //StringTokenizer palabrass = new StringTokenizer(txt_entrada.getText());
        
        reemplazar = JOptionPane.showInputDialog(rootPane, Integer.toString(conta)+" coincidencias encontradas\n"+"Con que palabra desea reemplazar el texto buscado:","Reemplazar",JOptionPane.PLAIN_MESSAGE);
        /*while(palabrass.hasMoreElements()){
            elemento = palabrass.nextToken();    
            if(elemento.equals(reemplazar)||elemento.equals(reemplazar+".")||elemento.equals(reemplazar+",")||elemento.equals(reemplazar+";")||elemento.equals(reemplazar+":")){
                txt_entrada.append(reemplazar+" ");
            }
            else{
                txt_entrada.append(elemento+" ");
            }
        }*/
        elemento = txt_entrada.getText();
        resultado = elemento.replace(buscar,reemplazar);
        txt_entrada.setText("");
        txt_entrada.setText(resultado);
    }//GEN-LAST:event_menu_reemplazarActionPerformed

    private void menu_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_nuevoActionPerformed
        txt_entrada.setText("");
        ficheroa = null;
        lbl_longitud.setText("");
        lbl_total.setText("");
        lbl_primer.setText("");
        lbl_ultima.setText("");
        lbl_central.setText("");
        lbl_primerap.setText("");
        lbl_centrop.setText("");
        lbl_ultimap.setText("");
        lbl_a.setText("");
        lbl_e.setText("");
        lbl_i.setText("");
        lbl_o.setText("");
        lbl_u.setText("");
        lbl_par.setText("");
        lbl_impar.setText("");
        txt_murcielago.setText("");
        lbl_longitudletras.setText("");
    }//GEN-LAST:event_menu_nuevoActionPerformed

    private void menu_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_abrirActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro =  new FileNameExtensionFilter(".txt","txt");
        fc.setFileFilter(filtro);
        fc.setMultiSelectionEnabled(false);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int seleccion = fc.showOpenDialog(this.getContentPane());
        if(seleccion == JFileChooser.APPROVE_OPTION){
            ficheroa = fc.getSelectedFile();
            try(FileReader fr = new FileReader(this.ficheroa)){
                String cadena = "";
                int valor = fr.read();
                while(valor != -1){
                    cadena += (char) valor;
                    valor = fr.read();
                }
                txt_entrada.setText(cadena);
            } catch (FileNotFoundException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_menu_abrirActionPerformed

    private void menu_guardarCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guardarCoActionPerformed
        abrirGuardar();
    }//GEN-LAST:event_menu_guardarCoActionPerformed

    private void menu_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guardarActionPerformed
        if(ficheroa == null){
            abrirGuardar();
        }else{
            escribirFichero();
        }            
    }//GEN-LAST:event_menu_guardarActionPerformed
    
    private void abrirGuardar(){
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro =  new FileNameExtensionFilter(".txt","txt");
        fc.setFileFilter(filtro);
            fc.setMultiSelectionEnabled(false);
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int seleccion = fc.showSaveDialog(this.getContentPane());
            if(seleccion == JFileChooser.APPROVE_OPTION){
                ficheroa = fc.getSelectedFile();
                escribirFichero();
                
            }
    }
    
    private void escribirFichero(){
        try(FileWriter fw = new FileWriter(ficheroa)){
            fw.write(txt_entrada.getText());
        } catch (IOException ex) {
            Logger.getLogger(frm_cadenas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_cadenas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_procesar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_central;
    private javax.swing.JLabel lbl_centrop;
    private javax.swing.JLabel lbl_e;
    private javax.swing.JLabel lbl_i;
    private javax.swing.JLabel lbl_impar;
    private javax.swing.JLabel lbl_longitud;
    private javax.swing.JLabel lbl_longitudletras;
    private javax.swing.JLabel lbl_o;
    private javax.swing.JLabel lbl_par;
    private javax.swing.JLabel lbl_primer;
    private javax.swing.JLabel lbl_primerap;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_u;
    private javax.swing.JLabel lbl_ultima;
    private javax.swing.JLabel lbl_ultimap;
    private javax.swing.JMenuItem menu_abrir;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenuBar menu_barra;
    private javax.swing.JMenuItem menu_buscar;
    private javax.swing.JMenuItem menu_copiar;
    private javax.swing.JMenuItem menu_cortar;
    private javax.swing.JMenu menu_editar;
    private javax.swing.JMenuItem menu_guardar;
    private javax.swing.JMenuItem menu_guardarCo;
    private javax.swing.JMenuItem menu_nuevo;
    private javax.swing.JMenuItem menu_pegar;
    private javax.swing.JMenuItem menu_reemplazar;
    private javax.swing.JTextArea txt_entrada;
    private javax.swing.JTextArea txt_murcielago;
    // End of variables declaration//GEN-END:variables
}
